server:
  port: 60000
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: newpark-sso
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://192.168.13.129:3306/newpark?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useUnicode=true&allowMultiQueries=true
    username: root
    password: '12345678'
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.13.129:8848 #Nacos服务注册中心地址
        group: dev
        namespace: ddc492bc-9d53-4330-b59c-8e2f3faffff7
      username: nacos
      password: nacos
  redis:
    database: 1
    timeout: 1000
    host: 192.168.13.129
    port: 36379
    password:
